package de.fraunhofer.fokus.oefit.particity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.fraunhofer.fokus.oefit.particity.model.AHCategories;
import de.fraunhofer.fokus.oefit.particity.service.AHCategoriesLocalServiceUtil;

/**
 * The extended model base implementation for the AHCategories service. Represents a row in the &quot;AHCATS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AHCategoriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHCategoriesImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.AHCategories
 * @generated
 */
public abstract class AHCategoriesBaseImpl extends AHCategoriesModelImpl
    implements AHCategories {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a a h categories model instance should use the {@link AHCategories} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AHCategoriesLocalServiceUtil.addAHCategories(this);
        } else {
            AHCategoriesLocalServiceUtil.updateAHCategories(this);
        }
    }
}
