package de.fraunhofer.fokus.oefit.particity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.fraunhofer.fokus.oefit.particity.model.AHOffer;
import de.fraunhofer.fokus.oefit.particity.service.AHOfferLocalServiceUtil;

/**
 * The extended model base implementation for the AHOffer service. Represents a row in the &quot;AHOFFER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AHOfferImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHOfferImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.AHOffer
 * @generated
 */
public abstract class AHOfferBaseImpl extends AHOfferModelImpl
    implements AHOffer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a a h offer model instance should use the {@link AHOffer} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AHOfferLocalServiceUtil.addAHOffer(this);
        } else {
            AHOfferLocalServiceUtil.updateAHOffer(this);
        }
    }
}
