package de.fraunhofer.fokus.oefit.particity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.fraunhofer.fokus.oefit.particity.model.AHOrg;
import de.fraunhofer.fokus.oefit.particity.service.AHOrgLocalServiceUtil;

/**
 * The extended model base implementation for the AHOrg service. Represents a row in the &quot;AHORG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AHOrgImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHOrgImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.AHOrg
 * @generated
 */
public abstract class AHOrgBaseImpl extends AHOrgModelImpl implements AHOrg {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a a h org model instance should use the {@link AHOrg} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AHOrgLocalServiceUtil.addAHOrg(this);
        } else {
            AHOrgLocalServiceUtil.updateAHOrg(this);
        }
    }
}
