/*
 * Copyright (c) 2015, Fraunhofer FOKUS
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * 
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * 
 * * Neither the name of particity nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 * 
 * @author sma
 */
package de.fraunhofer.fokus.oefit.adhoc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHAddr service. Represents a row in the &quot;AHADDR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.adhoc.model.impl.AHAddrModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.adhoc.model.impl.AHAddrImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHAddr
 * @see de.fraunhofer.fokus.oefit.adhoc.model.impl.AHAddrImpl
 * @see de.fraunhofer.fokus.oefit.adhoc.model.impl.AHAddrModelImpl
 * @generated
 */
public interface AHAddrModel extends BaseModel<AHAddr> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h addr model instance should use the {@link AHAddr} interface instead.
     */

    /**
     * Returns the primary key of this a h addr.
     *
     * @return the primary key of this a h addr
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h addr.
     *
     * @param primaryKey the primary key of this a h addr
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the addr ID of this a h addr.
     *
     * @return the addr ID of this a h addr
     */
    public long getAddrId();

    /**
     * Sets the addr ID of this a h addr.
     *
     * @param addrId the addr ID of this a h addr
     */
    public void setAddrId(long addrId);

    /**
     * Returns the street of this a h addr.
     *
     * @return the street of this a h addr
     */
    @AutoEscape
    public String getStreet();

    /**
     * Sets the street of this a h addr.
     *
     * @param street the street of this a h addr
     */
    public void setStreet(String street);

    /**
     * Returns the number of this a h addr.
     *
     * @return the number of this a h addr
     */
    @AutoEscape
    public String getNumber();

    /**
     * Sets the number of this a h addr.
     *
     * @param number the number of this a h addr
     */
    public void setNumber(String number);

    /**
     * Returns the coord lat of this a h addr.
     *
     * @return the coord lat of this a h addr
     */
    @AutoEscape
    public String getCoordLat();

    /**
     * Sets the coord lat of this a h addr.
     *
     * @param coordLat the coord lat of this a h addr
     */
    public void setCoordLat(String coordLat);

    /**
     * Returns the coord lon of this a h addr.
     *
     * @return the coord lon of this a h addr
     */
    @AutoEscape
    public String getCoordLon();

    /**
     * Sets the coord lon of this a h addr.
     *
     * @param coordLon the coord lon of this a h addr
     */
    public void setCoordLon(String coordLon);

    /**
     * Returns the region ID of this a h addr.
     *
     * @return the region ID of this a h addr
     */
    public long getRegionId();

    /**
     * Sets the region ID of this a h addr.
     *
     * @param regionId the region ID of this a h addr
     */
    public void setRegionId(long regionId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHAddr ahAddr);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHAddr> toCacheModel();

    @Override
    public AHAddr toEscapedModel();

    @Override
    public AHAddr toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
