/*
 * Copyright (c) 2015, Fraunhofer FOKUS
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * 
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * 
 * * Neither the name of particity nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 * 
 * @author sma
 */
package de.fraunhofer.fokus.oefit.adhoc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.fraunhofer.fokus.oefit.adhoc.service.persistence.AHRegionPK;

import java.io.Serializable;

/**
 * The base model interface for the AHRegion service. Represents a row in the &quot;AHREGION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.adhoc.model.impl.AHRegionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.adhoc.model.impl.AHRegionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHRegion
 * @see de.fraunhofer.fokus.oefit.adhoc.model.impl.AHRegionImpl
 * @see de.fraunhofer.fokus.oefit.adhoc.model.impl.AHRegionModelImpl
 * @generated
 */
public interface AHRegionModel extends BaseModel<AHRegion> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h region model instance should use the {@link AHRegion} interface instead.
     */

    /**
     * Returns the primary key of this a h region.
     *
     * @return the primary key of this a h region
     */
    public AHRegionPK getPrimaryKey();

    /**
     * Sets the primary key of this a h region.
     *
     * @param primaryKey the primary key of this a h region
     */
    public void setPrimaryKey(AHRegionPK primaryKey);

    /**
     * Returns the region ID of this a h region.
     *
     * @return the region ID of this a h region
     */
    public long getRegionId();

    /**
     * Sets the region ID of this a h region.
     *
     * @param regionId the region ID of this a h region
     */
    public void setRegionId(long regionId);

    /**
     * Returns the zip of this a h region.
     *
     * @return the zip of this a h region
     */
    public int getZip();

    /**
     * Sets the zip of this a h region.
     *
     * @param zip the zip of this a h region
     */
    public void setZip(int zip);

    /**
     * Returns the city of this a h region.
     *
     * @return the city of this a h region
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this a h region.
     *
     * @param city the city of this a h region
     */
    public void setCity(String city);

    /**
     * Returns the country of this a h region.
     *
     * @return the country of this a h region
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this a h region.
     *
     * @param country the country of this a h region
     */
    public void setCountry(String country);

    /**
     * Returns the permissions of this a h region.
     *
     * @return the permissions of this a h region
     */
    public int getPermissions();

    /**
     * Sets the permissions of this a h region.
     *
     * @param permissions the permissions of this a h region
     */
    public void setPermissions(int permissions);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHRegion ahRegion);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHRegion> toCacheModel();

    @Override
    public AHRegion toEscapedModel();

    @Override
    public AHRegion toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
