package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHAddr service. Represents a row in the &quot;AHADDR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHAddrModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHAddrImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHAddr
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHAddrImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHAddrModelImpl
 * @generated
 */
public interface AHAddrModel extends BaseModel<AHAddr> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h addr model instance should use the {@link AHAddr} interface instead.
     */

    /**
     * Returns the primary key of this a h addr.
     *
     * @return the primary key of this a h addr
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h addr.
     *
     * @param primaryKey the primary key of this a h addr
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the addr ID of this a h addr.
     *
     * @return the addr ID of this a h addr
     */
    public long getAddrId();

    /**
     * Sets the addr ID of this a h addr.
     *
     * @param addrId the addr ID of this a h addr
     */
    public void setAddrId(long addrId);

    /**
     * Returns the street of this a h addr.
     *
     * @return the street of this a h addr
     */
    @AutoEscape
    public String getStreet();

    /**
     * Sets the street of this a h addr.
     *
     * @param street the street of this a h addr
     */
    public void setStreet(String street);

    /**
     * Returns the number of this a h addr.
     *
     * @return the number of this a h addr
     */
    @AutoEscape
    public String getNumber();

    /**
     * Sets the number of this a h addr.
     *
     * @param number the number of this a h addr
     */
    public void setNumber(String number);

    /**
     * Returns the coord lat of this a h addr.
     *
     * @return the coord lat of this a h addr
     */
    public float getCoordLat();

    /**
     * Sets the coord lat of this a h addr.
     *
     * @param coordLat the coord lat of this a h addr
     */
    public void setCoordLat(float coordLat);

    /**
     * Returns the coord lon of this a h addr.
     *
     * @return the coord lon of this a h addr
     */
    public float getCoordLon();

    /**
     * Sets the coord lon of this a h addr.
     *
     * @param coordLon the coord lon of this a h addr
     */
    public void setCoordLon(float coordLon);

    /**
     * Returns the region ID of this a h addr.
     *
     * @return the region ID of this a h addr
     */
    public long getRegionId();

    /**
     * Sets the region ID of this a h addr.
     *
     * @param regionId the region ID of this a h addr
     */
    public void setRegionId(long regionId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.fraunhofer.fokus.oefit.particity.model.AHAddr ahAddr);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.fraunhofer.fokus.oefit.particity.model.AHAddr> toCacheModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHAddr toEscapedModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHAddr toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
