package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHCatEntries service. Represents a row in the &quot;AHCITEM&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHCatEntriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHCatEntriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHCatEntries
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHCatEntriesImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHCatEntriesModelImpl
 * @generated
 */
public interface AHCatEntriesModel extends BaseModel<AHCatEntries> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h cat entries model instance should use the {@link AHCatEntries} interface instead.
     */

    /**
     * Returns the primary key of this a h cat entries.
     *
     * @return the primary key of this a h cat entries
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h cat entries.
     *
     * @param primaryKey the primary key of this a h cat entries
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the item ID of this a h cat entries.
     *
     * @return the item ID of this a h cat entries
     */
    public long getItemId();

    /**
     * Sets the item ID of this a h cat entries.
     *
     * @param itemId the item ID of this a h cat entries
     */
    public void setItemId(long itemId);

    /**
     * Returns the cat ID of this a h cat entries.
     *
     * @return the cat ID of this a h cat entries
     */
    public long getCatId();

    /**
     * Sets the cat ID of this a h cat entries.
     *
     * @param catId the cat ID of this a h cat entries
     */
    public void setCatId(long catId);

    /**
     * Returns the name of this a h cat entries.
     *
     * @return the name of this a h cat entries
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this a h cat entries.
     *
     * @param name the name of this a h cat entries
     */
    public void setName(String name);

    /**
     * Returns the descr of this a h cat entries.
     *
     * @return the descr of this a h cat entries
     */
    @AutoEscape
    public String getDescr();

    /**
     * Sets the descr of this a h cat entries.
     *
     * @param descr the descr of this a h cat entries
     */
    public void setDescr(String descr);

    /**
     * Returns the parent ID of this a h cat entries.
     *
     * @return the parent ID of this a h cat entries
     */
    public long getParentId();

    /**
     * Sets the parent ID of this a h cat entries.
     *
     * @param parentId the parent ID of this a h cat entries
     */
    public void setParentId(long parentId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHCatEntries ahCatEntries);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHCatEntries> toCacheModel();

    @Override
    public AHCatEntries toEscapedModel();

    @Override
    public AHCatEntries toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
