package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHContact service. Represents a row in the &quot;AHCONTACT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHContact
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHContactImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHContactModelImpl
 * @generated
 */
public interface AHContactModel extends BaseModel<AHContact> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h contact model instance should use the {@link AHContact} interface instead.
     */

    /**
     * Returns the primary key of this a h contact.
     *
     * @return the primary key of this a h contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h contact.
     *
     * @param primaryKey the primary key of this a h contact
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contact ID of this a h contact.
     *
     * @return the contact ID of this a h contact
     */
    public long getContactId();

    /**
     * Sets the contact ID of this a h contact.
     *
     * @param contactId the contact ID of this a h contact
     */
    public void setContactId(long contactId);

    /**
     * Returns the forename of this a h contact.
     *
     * @return the forename of this a h contact
     */
    @AutoEscape
    public String getForename();

    /**
     * Sets the forename of this a h contact.
     *
     * @param forename the forename of this a h contact
     */
    public void setForename(String forename);

    /**
     * Returns the surname of this a h contact.
     *
     * @return the surname of this a h contact
     */
    @AutoEscape
    public String getSurname();

    /**
     * Sets the surname of this a h contact.
     *
     * @param surname the surname of this a h contact
     */
    public void setSurname(String surname);

    /**
     * Returns the tel of this a h contact.
     *
     * @return the tel of this a h contact
     */
    @AutoEscape
    public String getTel();

    /**
     * Sets the tel of this a h contact.
     *
     * @param tel the tel of this a h contact
     */
    public void setTel(String tel);

    /**
     * Returns the mobile of this a h contact.
     *
     * @return the mobile of this a h contact
     */
    @AutoEscape
    public String getMobile();

    /**
     * Sets the mobile of this a h contact.
     *
     * @param mobile the mobile of this a h contact
     */
    public void setMobile(String mobile);

    /**
     * Returns the fax of this a h contact.
     *
     * @return the fax of this a h contact
     */
    @AutoEscape
    public String getFax();

    /**
     * Sets the fax of this a h contact.
     *
     * @param fax the fax of this a h contact
     */
    public void setFax(String fax);

    /**
     * Returns the email of this a h contact.
     *
     * @return the email of this a h contact
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this a h contact.
     *
     * @param email the email of this a h contact
     */
    public void setEmail(String email);

    /**
     * Returns the www of this a h contact.
     *
     * @return the www of this a h contact
     */
    @AutoEscape
    public String getWww();

    /**
     * Sets the www of this a h contact.
     *
     * @param www the www of this a h contact
     */
    public void setWww(String www);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.fraunhofer.fokus.oefit.particity.model.AHContact ahContact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.fraunhofer.fokus.oefit.particity.model.AHContact> toCacheModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHContact toEscapedModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHContact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
