package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHOffer service. Represents a row in the &quot;AHOFFER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHOfferModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHOfferImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHOffer
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHOfferImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHOfferModelImpl
 * @generated
 */
public interface AHOfferModel extends BaseModel<AHOffer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h offer model instance should use the {@link AHOffer} interface instead.
     */

    /**
     * Returns the primary key of this a h offer.
     *
     * @return the primary key of this a h offer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h offer.
     *
     * @param primaryKey the primary key of this a h offer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the offer ID of this a h offer.
     *
     * @return the offer ID of this a h offer
     */
    public long getOfferId();

    /**
     * Sets the offer ID of this a h offer.
     *
     * @param offerId the offer ID of this a h offer
     */
    public void setOfferId(long offerId);

    /**
     * Returns the title of this a h offer.
     *
     * @return the title of this a h offer
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this a h offer.
     *
     * @param title the title of this a h offer
     */
    public void setTitle(String title);

    /**
     * Returns the description of this a h offer.
     *
     * @return the description of this a h offer
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this a h offer.
     *
     * @param description the description of this a h offer
     */
    public void setDescription(String description);

    /**
     * Returns the work time of this a h offer.
     *
     * @return the work time of this a h offer
     */
    @AutoEscape
    public String getWorkTime();

    /**
     * Sets the work time of this a h offer.
     *
     * @param workTime the work time of this a h offer
     */
    public void setWorkTime(String workTime);

    /**
     * Returns the work type of this a h offer.
     *
     * @return the work type of this a h offer
     */
    public int getWorkType();

    /**
     * Sets the work type of this a h offer.
     *
     * @param workType the work type of this a h offer
     */
    public void setWorkType(int workType);

    /**
     * Returns the type of this a h offer.
     *
     * @return the type of this a h offer
     */
    public int getType();

    /**
     * Sets the type of this a h offer.
     *
     * @param type the type of this a h offer
     */
    public void setType(int type);

    /**
     * Returns the status of this a h offer.
     *
     * @return the status of this a h offer
     */
    public int getStatus();

    /**
     * Sets the status of this a h offer.
     *
     * @param status the status of this a h offer
     */
    public void setStatus(int status);

    /**
     * Returns the social status of this a h offer.
     *
     * @return the social status of this a h offer
     */
    public int getSocialStatus();

    /**
     * Sets the social status of this a h offer.
     *
     * @param socialStatus the social status of this a h offer
     */
    public void setSocialStatus(int socialStatus);

    /**
     * Returns the created of this a h offer.
     *
     * @return the created of this a h offer
     */
    public long getCreated();

    /**
     * Sets the created of this a h offer.
     *
     * @param created the created of this a h offer
     */
    public void setCreated(long created);

    /**
     * Returns the updated of this a h offer.
     *
     * @return the updated of this a h offer
     */
    public long getUpdated();

    /**
     * Sets the updated of this a h offer.
     *
     * @param updated the updated of this a h offer
     */
    public void setUpdated(long updated);

    /**
     * Returns the expires of this a h offer.
     *
     * @return the expires of this a h offer
     */
    public long getExpires();

    /**
     * Sets the expires of this a h offer.
     *
     * @param expires the expires of this a h offer
     */
    public void setExpires(long expires);

    /**
     * Returns the publish of this a h offer.
     *
     * @return the publish of this a h offer
     */
    public long getPublish();

    /**
     * Sets the publish of this a h offer.
     *
     * @param publish the publish of this a h offer
     */
    public void setPublish(long publish);

    /**
     * Returns the adress ID of this a h offer.
     *
     * @return the adress ID of this a h offer
     */
    public long getAdressId();

    /**
     * Sets the adress ID of this a h offer.
     *
     * @param adressId the adress ID of this a h offer
     */
    public void setAdressId(long adressId);

    /**
     * Returns the contact ID of this a h offer.
     *
     * @return the contact ID of this a h offer
     */
    public long getContactId();

    /**
     * Sets the contact ID of this a h offer.
     *
     * @param contactId the contact ID of this a h offer
     */
    public void setContactId(long contactId);

    /**
     * Returns the snd contact ID of this a h offer.
     *
     * @return the snd contact ID of this a h offer
     */
    public long getSndContactId();

    /**
     * Sets the snd contact ID of this a h offer.
     *
     * @param sndContactId the snd contact ID of this a h offer
     */
    public void setSndContactId(long sndContactId);

    /**
     * Returns the contact agency of this a h offer.
     *
     * @return the contact agency of this a h offer
     */
    public boolean getContactAgency();

    /**
     * Returns <code>true</code> if this a h offer is contact agency.
     *
     * @return <code>true</code> if this a h offer is contact agency; <code>false</code> otherwise
     */
    public boolean isContactAgency();

    /**
     * Sets whether this a h offer is contact agency.
     *
     * @param contactAgency the contact agency of this a h offer
     */
    public void setContactAgency(boolean contactAgency);

    /**
     * Returns the org ID of this a h offer.
     *
     * @return the org ID of this a h offer
     */
    public long getOrgId();

    /**
     * Sets the org ID of this a h offer.
     *
     * @param orgId the org ID of this a h offer
     */
    public void setOrgId(long orgId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        de.fraunhofer.fokus.oefit.particity.model.AHOffer ahOffer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<de.fraunhofer.fokus.oefit.particity.model.AHOffer> toCacheModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHOffer toEscapedModel();

    @Override
    public de.fraunhofer.fokus.oefit.particity.model.AHOffer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
