package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import de.fraunhofer.fokus.oefit.particity.service.persistence.AHRegionPK;

import java.io.Serializable;

/**
 * The base model interface for the AHRegion service. Represents a row in the &quot;AHREGION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHRegionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHRegionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHRegion
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHRegionImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHRegionModelImpl
 * @generated
 */
public interface AHRegionModel extends BaseModel<AHRegion> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h region model instance should use the {@link AHRegion} interface instead.
     */

    /**
     * Returns the primary key of this a h region.
     *
     * @return the primary key of this a h region
     */
    public AHRegionPK getPrimaryKey();

    /**
     * Sets the primary key of this a h region.
     *
     * @param primaryKey the primary key of this a h region
     */
    public void setPrimaryKey(AHRegionPK primaryKey);

    /**
     * Returns the region ID of this a h region.
     *
     * @return the region ID of this a h region
     */
    public long getRegionId();

    /**
     * Sets the region ID of this a h region.
     *
     * @param regionId the region ID of this a h region
     */
    public void setRegionId(long regionId);

    /**
     * Returns the zip of this a h region.
     *
     * @return the zip of this a h region
     */
    @AutoEscape
    public String getZip();

    /**
     * Sets the zip of this a h region.
     *
     * @param zip the zip of this a h region
     */
    public void setZip(String zip);

    /**
     * Returns the city of this a h region.
     *
     * @return the city of this a h region
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this a h region.
     *
     * @param city the city of this a h region
     */
    public void setCity(String city);

    /**
     * Returns the country of this a h region.
     *
     * @return the country of this a h region
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this a h region.
     *
     * @param country the country of this a h region
     */
    public void setCountry(String country);

    /**
     * Returns the permissions of this a h region.
     *
     * @return the permissions of this a h region
     */
    public int getPermissions();

    /**
     * Sets the permissions of this a h region.
     *
     * @param permissions the permissions of this a h region
     */
    public void setPermissions(int permissions);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHRegion ahRegion);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHRegion> toCacheModel();

    @Override
    public AHRegion toEscapedModel();

    @Override
    public AHRegion toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
