package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHSubscription service. Represents a row in the &quot;AHSUBSCR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHSubscriptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHSubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHSubscription
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHSubscriptionImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHSubscriptionModelImpl
 * @generated
 */
public interface AHSubscriptionModel extends BaseModel<AHSubscription> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h subscription model instance should use the {@link AHSubscription} interface instead.
     */

    /**
     * Returns the primary key of this a h subscription.
     *
     * @return the primary key of this a h subscription
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h subscription.
     *
     * @param primaryKey the primary key of this a h subscription
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the sub ID of this a h subscription.
     *
     * @return the sub ID of this a h subscription
     */
    public long getSubId();

    /**
     * Sets the sub ID of this a h subscription.
     *
     * @param subId the sub ID of this a h subscription
     */
    public void setSubId(long subId);

    /**
     * Returns the uuid of this a h subscription.
     *
     * @return the uuid of this a h subscription
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this a h subscription.
     *
     * @param uuid the uuid of this a h subscription
     */
    public void setUuid(String uuid);

    /**
     * Returns the email of this a h subscription.
     *
     * @return the email of this a h subscription
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this a h subscription.
     *
     * @param email the email of this a h subscription
     */
    public void setEmail(String email);

    /**
     * Returns the status of this a h subscription.
     *
     * @return the status of this a h subscription
     */
    public int getStatus();

    /**
     * Sets the status of this a h subscription.
     *
     * @param status the status of this a h subscription
     */
    public void setStatus(int status);

    /**
     * Returns the created of this a h subscription.
     *
     * @return the created of this a h subscription
     */
    public long getCreated();

    /**
     * Sets the created of this a h subscription.
     *
     * @param created the created of this a h subscription
     */
    public void setCreated(long created);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHSubscription ahSubscription);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHSubscription> toCacheModel();

    @Override
    public AHSubscription toEscapedModel();

    @Override
    public AHSubscription toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
