package de.fraunhofer.fokus.oefit.particity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.fraunhofer.fokus.oefit.particity.model.AHAddr;
import de.fraunhofer.fokus.oefit.particity.service.AHAddrLocalServiceUtil;

/**
 * The extended model base implementation for the AHAddr service. Represents a row in the &quot;AHADDR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AHAddrImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHAddrImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.AHAddr
 * @generated
 */
public abstract class AHAddrBaseImpl extends AHAddrModelImpl implements AHAddr {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a a h addr model instance should use the {@link AHAddr} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AHAddrLocalServiceUtil.addAHAddr(this);
        } else {
            AHAddrLocalServiceUtil.updateAHAddr(this);
        }
    }
}
