package de.fraunhofer.fokus.oefit.particity.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import de.fraunhofer.fokus.oefit.particity.model.AHRegion;
import de.fraunhofer.fokus.oefit.particity.service.AHRegionLocalServiceUtil;

/**
 * The extended model base implementation for the AHRegion service. Represents a row in the &quot;AHREGION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AHRegionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHRegionImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.AHRegion
 * @generated
 */
public abstract class AHRegionBaseImpl extends AHRegionModelImpl
    implements AHRegion {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a a h region model instance should use the {@link AHRegion} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AHRegionLocalServiceUtil.addAHRegion(this);
        } else {
            AHRegionLocalServiceUtil.updateAHRegion(this);
        }
    }
}
