//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.20 at 05:13:31 PM CEST 
//


package de.particity.schemagen.impexpv100;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportExportRoot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportExportRoot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Organisation" type="{http://github.com/fraunhoferfokus/particity/ImportExport}OrganisationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Offer" type="{http://github.com/fraunhoferfokus/particity/ImportExport}OfferType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Category" type="{http://github.com/fraunhoferfokus/particity/ImportExport}CategoryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Subscription" type="{http://github.com/fraunhoferfokus/particity/ImportExport}SubscriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Config" type="{http://github.com/fraunhoferfokus/particity/ImportExport}ConfigurationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportExportRoot", propOrder = {
    "organisations",
    "offers",
    "categories",
    "subscriptions",
    "configs"
})
public class ImportExportRoot {

    @XmlElement(name = "Organisation")
    protected List<OrganisationType> organisations;
    @XmlElement(name = "Offer")
    protected List<OfferType> offers;
    @XmlElement(name = "Category")
    protected List<CategoryType> categories;
    @XmlElement(name = "Subscription")
    protected List<SubscriptionType> subscriptions;
    @XmlElement(name = "Config")
    protected List<ConfigurationType> configs;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the organisations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganisationType }
     * 
     * 
     */
    public List<OrganisationType> getOrganisations() {
        if (organisations == null) {
            organisations = new ArrayList<OrganisationType>();
        }
        return this.organisations;
    }

    /**
     * Gets the value of the offers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferType }
     * 
     * 
     */
    public List<OfferType> getOffers() {
        if (offers == null) {
            offers = new ArrayList<OfferType>();
        }
        return this.offers;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryType }
     * 
     * 
     */
    public List<CategoryType> getCategories() {
        if (categories == null) {
            categories = new ArrayList<CategoryType>();
        }
        return this.categories;
    }

    /**
     * Gets the value of the subscriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubscriptionType }
     * 
     * 
     */
    public List<SubscriptionType> getSubscriptions() {
        if (subscriptions == null) {
            subscriptions = new ArrayList<SubscriptionType>();
        }
        return this.subscriptions;
    }

    /**
     * Gets the value of the configs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationType }
     * 
     * 
     */
    public List<ConfigurationType> getConfigs() {
        if (configs == null) {
            configs = new ArrayList<ConfigurationType>();
        }
        return this.configs;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
