package de.fraunhofer.fokus.oefit.particity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AHCategories service. Represents a row in the &quot;AHCATS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHCategoriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.fraunhofer.fokus.oefit.particity.model.impl.AHCategoriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AHCategories
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHCategoriesImpl
 * @see de.fraunhofer.fokus.oefit.particity.model.impl.AHCategoriesModelImpl
 * @generated
 */
public interface AHCategoriesModel extends BaseModel<AHCategories> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a a h categories model instance should use the {@link AHCategories} interface instead.
     */

    /**
     * Returns the primary key of this a h categories.
     *
     * @return the primary key of this a h categories
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this a h categories.
     *
     * @param primaryKey the primary key of this a h categories
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the cat ID of this a h categories.
     *
     * @return the cat ID of this a h categories
     */
    public long getCatId();

    /**
     * Sets the cat ID of this a h categories.
     *
     * @param catId the cat ID of this a h categories
     */
    public void setCatId(long catId);

    /**
     * Returns the name of this a h categories.
     *
     * @return the name of this a h categories
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this a h categories.
     *
     * @param name the name of this a h categories
     */
    public void setName(String name);

    /**
     * Returns the descr of this a h categories.
     *
     * @return the descr of this a h categories
     */
    @AutoEscape
    public String getDescr();

    /**
     * Sets the descr of this a h categories.
     *
     * @param descr the descr of this a h categories
     */
    public void setDescr(String descr);

    /**
     * Returns the type of this a h categories.
     *
     * @return the type of this a h categories
     */
    public int getType();

    /**
     * Sets the type of this a h categories.
     *
     * @param type the type of this a h categories
     */
    public void setType(int type);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(AHCategories ahCategories);

    @Override
    public int hashCode();

    @Override
    public CacheModel<AHCategories> toCacheModel();

    @Override
    public AHCategories toEscapedModel();

    @Override
    public AHCategories toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
