//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 02:31:37 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://github.com/fraunhoferfokus/particity/ImportExport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.particity.schemagen.impexpv100;
